# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rankties <- function(y, x, n, m, t, delta, type, print, v) {
    .Call(`_ranktiesR_rankties`, y, x, n, m, t, delta, type, print, v)
}

