# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genz <- function(a, b, mu, sigma, epsilon, alpha, nmin, nmax) {
    .Call(`_ranktiesR_genz`, a, b, mu, sigma, epsilon, alpha, nmin, nmax)
}

rankties <- function(y, x, z, n, m, t, delta, scale, type, h, print) {
    .Call(`_ranktiesR_rankties`, y, x, z, n, m, t, delta, scale, type, h, print)
}

ranktiesloglik <- function(y, x, theta, type, delta, b, m) {
    .Call(`_ranktiesR_ranktiesloglik`, y, x, theta, type, delta, b, m)
}

foo <- function(m, s, low, upp, n) {
    .Call(`_ranktiesR_foo`, m, s, low, upp, n)
}

residuals <- function(y, x, theta, type, delta, n) {
    .Call(`_ranktiesR_residuals`, y, x, theta, type, delta, n)
}

