# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ranktiesmodel <- function(y, x, n, m, t, delta, scale, type, h, print) {
    .Call(`_ranktiesR_ranktiesmodel`, y, x, n, m, t, delta, scale, type, h, print)
}

ranktiesloglik <- function(y, x, w, theta, type, delta, b, m) {
    .Call(`_ranktiesR_ranktiesloglik`, y, x, w, theta, type, delta, b, m)
}

residuals <- function(y, x, theta, type, delta, n) {
    .Call(`_ranktiesR_residuals`, y, x, theta, type, delta, n)
}

rankmodel <- function(y, x, n, m, t, print, h) {
    .Call(`_ranktiesR_rankmodel`, y, x, n, m, t, print, h)
}

